--migrate:up
ALTER TABLE config ADD COLUMN IF NOT EXISTS head_html TEXT NOT NULL DEFAULT '';
ALTER TABLE config ADD COLUMN IF NOT EXISTS foot_html TEXT NOT NULL DEFAULT '';
ALTER TABLE config ADD COLUMN IF NOT EXISTS meta_html TEXT NOT NULL DEFAULT '';
ALTER TABLE config ADD COLUMN IF NOT EXISTS limitme_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE config ADD COLUMN IF NOT EXISTS limitme_from INTEGER NOT NULL DEFAULT 0;
ALTER TABLE config ADD COLUMN IF NOT EXISTS limitme_to INTEGER NOT NULL DEFAULT 0;
ALTER TABLE config ADD COLUMN IF NOT EXISTS search_captcha_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE config ADD COLUMN IF NOT EXISTS read_type TEXT NOT NULL DEFAULT '5ch';
ALTER TABLE config ADD COLUMN IF NOT EXISTS auto_discover_threads BOOLEAN NOT NULL DEFAULT TRUE;

--migrate:down
ALTER TABLE config DROP COLUMN IF EXISTS auto_discover_threads;
ALTER TABLE config DROP COLUMN IF EXISTS read_type;
ALTER TABLE config DROP COLUMN IF EXISTS search_captcha_enabled;
ALTER TABLE config DROP COLUMN IF EXISTS limitme_to;
ALTER TABLE config DROP COLUMN IF EXISTS limitme_from;
ALTER TABLE config DROP COLUMN IF EXISTS limitme_enabled;
ALTER TABLE config DROP COLUMN IF EXISTS meta_html;
ALTER TABLE config DROP COLUMN IF EXISTS foot_html;
ALTER TABLE config DROP COLUMN IF EXISTS head_html;
