import { ok, err } from "neverthrow";

import { DatabaseError } from "../../shared/types/Error";

import type { VakContext } from "../../shared/types/VakContext";
import type { WriteNormalConfig } from "../domain/write/WriteNormalConfig";
import type { Result } from "neverthrow";

export const updateNormalConfigRepository = async (
  { sql, logger }: VakContext,
  config: WriteNormalConfig
): Promise<Result<undefined, Error>> => {
  const {
    boardName,
    localRule,
    defaultAuthorName,
    maxContentLength,
    maxLines,
    maxLineWidth,
    maxAnchors,
    captchaProvider,
    captchaSiteKey,
    captchaSecretKey,
    enableDnsbl,
    dnsblHostnames,
    enableVpnDetection,
    referrerCushion,
    headHtml,
    footHtml,
    metaHtml,
    subtitle,
    faviconUrl,
    boardImageUrl,
    boardImageLinkUrl,
    bgColor,
    textColor,
    linkColor,
    nameColor,
    enableTwitterWidgets,
    limitmeEnabled,
    limitmeFrom,
    limitmeTo,
    searchCaptchaEnabled,
    readType,
    autoDiscoverThreads,
    bgColor2,
    titleColor,
    capColor,
    postBgColor,
    anchorColor,
    indexBgColor,
    createBgColor,
    menuBgColor,
    menuTextColor,
    titleId,
    msecDisplay,
    hideHits,
    prText,
    prLink,
    maxNameLength,
    maxMailLength,
    maxSubjectLength,
    lineMaxChars,
    submax,
    datmax,
    nanashiCheck,
    sambaTime,
    houshiTime,
    tatesugiHour,
    tatesugiCount,
    tatesugiClose,
    tatesugiCloseCount,
    slipEnabled,
    slipDefaultLevel,
    dispIp,
    beEnabled,
    voteEnabled,
    omikujiEnabled,
    tasukeruyoEnabled,
    hideOp,
    imgTag,
    twitterEmbed,
    movieEmbed,
    urlToTitle,
    autoFall,
    captchaPerBoard,
    usecaptchaOnAdmin,
    highLight,
    weekdayChars,
    tripColumn,
  } = config;

  logger.debug({
    operation: "updateNormalConfig",
    boardName: boardName.val,
    defaultAuthorName: defaultAuthorName.val,
    maxContentLength: maxContentLength.val,
    message: "Updating configuration in database",
  });

  try {
        await sql`
            UPDATE
                config
            SET
                board_name = ${boardName.val},
                local_rule = ${localRule.val},
                nanashi_name = ${defaultAuthorName.val},
                max_content_length = ${maxContentLength.val},
                max_lines = ${maxLines},
                max_line_width = ${maxLineWidth},
                max_anchors = ${maxAnchors},
                captcha_provider = ${captchaProvider},
                captcha_site_key = ${captchaSiteKey},
                captcha_secret_key = ${captchaSecretKey},
                enable_dnsbl = ${enableDnsbl},
                dnsbl_hostnames = ${dnsblHostnames},
                enable_vpn_detection = ${enableVpnDetection},
                referrer_cushion = ${referrerCushion},
                head_html = ${headHtml},
                foot_html = ${footHtml},
                meta_html = ${metaHtml},
                subtitle = ${subtitle},
                favicon_url = ${faviconUrl},
                board_image_url = ${boardImageUrl},
                board_image_link_url = ${boardImageLinkUrl},
                bg_color = ${bgColor},
                text_color = ${textColor},
                link_color = ${linkColor},
                name_color = ${nameColor},
                enable_twitter_widgets = ${enableTwitterWidgets},
                limitme_enabled = ${limitmeEnabled},
                limitme_from = ${limitmeFrom},
                limitme_to = ${limitmeTo},
                search_captcha_enabled = ${searchCaptchaEnabled},
                read_type = ${readType},
                auto_discover_threads = ${autoDiscoverThreads},
                bg_color2 = ${bgColor2},
                title_color = ${titleColor},
                cap_color = ${capColor},
                post_bg_color = ${postBgColor},
                anchor_color = ${anchorColor},
                index_bg_color = ${indexBgColor},
                create_bg_color = ${createBgColor},
                menu_bg_color = ${menuBgColor},
                menu_text_color = ${menuTextColor},
                title_id = ${titleId},
                msec_display = ${msecDisplay},
                hide_hits = ${hideHits},
                pr_text = ${prText},
                pr_link = ${prLink},
                max_name_length = ${maxNameLength},
                max_mail_length = ${maxMailLength},
                max_subject_length = ${maxSubjectLength},
                line_max_chars = ${lineMaxChars},
                submax = ${submax},
                datmax = ${datmax},
                nanashi_check = ${nanashiCheck},
                samba_time = ${sambaTime},
                houshi_time = ${houshiTime},
                tatesugi_hour = ${tatesugiHour},
                tatesugi_count = ${tatesugiCount},
                tatesugi_close = ${tatesugiClose},
                tatesugi_close_count = ${tatesugiCloseCount},
                slip_enabled = ${slipEnabled},
                slip_default_level = ${slipDefaultLevel},
                disp_ip = ${dispIp},
                be_enabled = ${beEnabled},
                vote_enabled = ${voteEnabled},
                omikuji_enabled = ${omikujiEnabled},
                tasukeruyo_enabled = ${tasukeruyoEnabled},
                hide_op = ${hideOp},
                img_tag = ${imgTag},
                twitter_embed = ${twitterEmbed},
                movie_embed = ${movieEmbed},
                url_to_title = ${urlToTitle},
                auto_fall = ${autoFall},
                captcha_per_board = ${captchaPerBoard},
                usecaptcha_on_admin = ${usecaptchaOnAdmin},
                high_light = ${highLight},
                weekday_chars = ${weekdayChars},
                trip_column = ${tripColumn}
        `;

    logger.info({
      operation: "updateNormalConfig",
      boardName: boardName.val,
      message: "Configuration updated successfully in database",
    });

    return ok(undefined);
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    logger.error({
      operation: "updateNormalConfig",
      error,
      message: `Database error while updating configuration: ${message}`,
    });
    return err(
      new DatabaseError(`設定の更新中にエラーが発生しました: ${message}`, error)
    );
  }
};
